
CREATE USER BANCO
  IDENTIFIED BY banco
  TEMPORARY TABLESPACE TEMP
  PROFILE DEFAULT
  ACCOUNT UNLOCK;
  -- 5 Roles for BANCO 
  GRANT IMP_FULL_DATABASE TO BANCO;
  GRANT RESOURCE TO BANCO;
  GRANT EXP_FULL_DATABASE TO BANCO;
  GRANT CONNECT TO BANCO;
  GRANT DBA TO BANCO;
  ALTER USER BANCO DEFAULT ROLE ALL;
  -- 27 System Privileges for BANCO 
  GRANT DROP ANY TRIGGER TO BANCO;
  GRANT CREATE PUBLIC SYNONYM TO BANCO;
  GRANT DROP ANY INDEX TO BANCO;
  GRANT INSERT ANY TABLE TO BANCO;
  GRANT CREATE ANY SEQUENCE TO BANCO;
  GRANT DROP ANY SYNONYM TO BANCO;
  GRANT CREATE ANY TRIGGER TO BANCO;
  GRANT UNLIMITED TABLESPACE TO BANCO;
  GRANT CREATE ANY PROCEDURE TO BANCO;
  GRANT DROP ANY VIEW TO BANCO;
  GRANT CREATE ANY VIEW TO BANCO;
  GRANT DELETE ANY TABLE TO BANCO;
  GRANT DROP ANY TABLE TO BANCO;
  GRANT CREATE ANY TABLE TO BANCO;
  GRANT EXECUTE ANY PROCEDURE TO BANCO;
  GRANT ALTER ANY TABLE TO BANCO;
  GRANT ALTER USER TO BANCO;
  GRANT ALTER ANY TRIGGER TO BANCO;
  GRANT DROP ANY PROCEDURE TO BANCO;
  GRANT ALTER ANY PROCEDURE TO BANCO;
  GRANT CREATE ANY INDEX TO BANCO;
  GRANT FORCE TRANSACTION TO BANCO;
  GRANT DROP PUBLIC SYNONYM TO BANCO;
  GRANT CREATE SESSION TO BANCO;
  GRANT UPDATE ANY TABLE TO BANCO;
  GRANT SELECT ANY TABLE TO BANCO;
  GRANT LOCK ANY TABLE TO BANCO;
